source 'https://rubygems.org'

gem 'pg'
gem 'activerecord', '~> 4.1.0'
gem 'active_record_tasks', '~> 1.1.0'
gem 'bourbon'
gem 'sass'
gem 'sinatra', '~> 1.4.5'
gem 'sinatra-contrib', '~> 1.4.2'
gem 'sinatra-flash'